### ISSUE TITLE
[1.9.4] Grave on ExtraUtilities2 Solar Panel causes crash

### ISSUE THREAD

**Issue by Melakion** [M4thG33k/TombManyGraves-NOT-FOR-1.9.4-#3]
http://pastebin.com/MAtSB0ud

Forge 1963
extrautils2-1.9.4-alpha-1.0.0a
TombManyGraves-1.9.4-2.1.1

**Comment by M4thG33k** [comment]
Interesting. I'll see what I can do about this tomorrow. Thanks for letting me know!

**Comment by M4thG33k** [comment]
Fixed in next update
